//f
function newBlock(name, blockType) {
	exports[name] = extend(blockType, name, {});
}
//distribution
log("0");
newBlock("duct-junction",DuctJunction);
newBlock("armored-bridge-conveyor",DuctBridge);
newBlock("armored-overflow-gate",OverflowDuct);
newBlock("armored-underflow-gate",OverflowDuct);
newBlock("armored-router",DuctRouter);
newBlock("armored-unloader",DirectionalUnloader);
newBlock("phase-unloader",Unloader);

log("1");
newBlock("silicide-duct",Duct);
newBlock("silicide-armored-duct",Duct);
newBlock("silicide-junction",Junction);
newBlock("silicide-bridge-conveyor",BufferedItemBridge);
newBlock("silicide-sorter",Sorter);
newBlock("silicide-inverted-sorter",Sorter);
newBlock("silicide-router",Router);
newBlock("silicide-distributor",Router);
newBlock("silicide-overflow-gate",OverflowGate);
newBlock("silicide-underflow-gate",OverflowGate);
newBlock("silicide-unloader",Unloader);
newBlock("silicide-item-source",ItemSource);
newBlock("silicide-item-void",ItemVoid);

log("2");
newBlock("rail",Conveyor);
newBlock("rail-junction",Junction);
newBlock("rail-router",DuctRouter);
newBlock("rail-overflow-gate",OverflowDuct);
newBlock("rail-underflow-gate",OverflowDuct);
newBlock("rail-bridge",ItemBridge);
newBlock("rail-unloader",DirectionalUnloader);
newBlock("stack-rail",StackConveyor);

log("3");
newBlock("silicide-rail",Conveyor);
newBlock("silicide-rail-junction",Junction);
newBlock("silicide-rail-router",DuctRouter);
newBlock("silicide-rail-overflow-gate",OverflowDuct);
newBlock("silicide-rail-underflow-gate",OverflowDuct);
newBlock("silicide-rail-bridge",ItemBridge);
newBlock("silicide-rail-unloader",DirectionalUnloader);
newBlock("silicide-stack-rail",StackConveyor);

log("4");
newBlock("chromium-conveyor",ArmoredConveyor);
newBlock("chromium-sorter",Sorter);
newBlock("cobalt-rail",Conveyor);
newBlock("cobalt-rail-underflow-gate",OverflowGate);
newBlock("cobalt-rail-bridge",ItemBridge);
newBlock("cobalt-rail-unloader",Unloader);
newBlock("multi-unloader",Unloader);
newBlock("mass-launcher",MassDriver);
newBlock("mass-railgun",MassDriver);
newBlock("warp-driver",MassDriver);

log("5");
newBlock("ferric-rail",ArmoredConveyor);
newBlock("ferric-conveyor",Conveyor);
newBlock("ferric-conveyor-armored",ArmoredConveyor);
newBlock("valve-cross",Junction);
newBlock("ferric-bridge",ItemBridge);
newBlock("valve-sort",Sorter);
newBlock("valve-inverted-sort",Sorter);
newBlock("valve-distribute",Router);
newBlock("valve-overflow",OverflowGate);
newBlock("valve-underflow",OverflowGate);
newBlock("valve-unload",Unloader);

//factories
log("6");
newBlock("cryo-pool",GenericCrafter);
newBlock("quartz-extractor",GenericCrafter);

log("7");
newBlock("isomorphic-press",GenericCrafter);
newBlock("hydraulic-press",GenericCrafter);
newBlock("quartz-separator",GenericCrafter);
newBlock("quartz-separator-large",GenericCrafter);
newBlock("isomorphic-smelter",GenericCrafter);
newBlock("substitution-chamber",GenericCrafter);
newBlock("silicide-crucible",GenericCrafter);
newBlock("silicide-mixer",GenericCrafter);
newBlock("coal-synthezer",GenericCrafter);
newBlock("carbon-shale-smelter",GenericCrafter);

log("8");
newBlock("salt-electrolyzer",GenericCrafter);
newBlock("melting-electrolyzer",GenericCrafter);
newBlock("surge-electrolyzer",GenericCrafter);
newBlock("gasification-chamber",GenericCrafter);
newBlock("sodium-carbon-fixator",GenericCrafter);
newBlock("titanium-extractor",GenericCrafter);
newBlock("cracking-compressor",GenericCrafter);
newBlock("chain-transferer",GenericCrafter);
newBlock("carbonization-chamber",GenericCrafter);

log("9");
newBlock("eddy-melter",GenericCrafter);
newBlock("decomposer",Separator);
newBlock("extractor",Separator);
newBlock("recycler",Separator);
newBlock("lava-cooler",GenericCrafter);
newBlock("catalyzon-crafter",GenericCrafter);

log("10");
newBlock("isomorphic-kiln",GenericCrafter);
newBlock("isomorphic-pulverizer",GenericCrafter);
newBlock("large-pulverizer",GenericCrafter);
newBlock("pyratiter",GenericCrafter);
newBlock("blaster",GenericCrafter);
newBlock("plant-press",GenericCrafter);
newBlock("spore-blender",GenericCrafter);
newBlock("cell-laboratory",GenericCrafter);
newBlock("nitroalkoss-reactor",GenericCrafter);
newBlock("fibralt-extender",GenericCrafter);
newBlock("fusion-refueller",GenericCrafter);
newBlock("fusion-disfueller",GenericCrafter);
newBlock("phase-loom",GenericCrafter);
newBlock("surge-coagulator",GenericCrafter);
newBlock("warper",GenericCrafter);

log("11");
newBlock("blast-furnace",GenericCrafter);
newBlock("multi-furnace",GenericCrafter);
//newBlock("reduction-chamber",GenericCrafter);
newBlock("centrifuge-kiln",GenericCrafter);
newBlock("reflector-thermolyzer",GenericCrafter);
newBlock("magnetic-separator",GenericCrafter);
newBlock("catalyzon-workshop",GenericCrafter);
newBlock("thermoplastic-compressor",HeatCrafter);

log("11.1");
newBlock("heat-conduct-conductor",HeatConductor);
newBlock("heat-conduct-distributor",HeatConductor);
newBlock("reactor-core",HeatProducer);

log("12");
newBlock("silicon-oxidator",GenericCrafter);
newBlock("eddy-mixer",GenericCrafter);
newBlock("filter",GenericCrafter);
newBlock("blender",GenericCrafter);
newBlock("concentrator",GenericCrafter);
newBlock("grinder",GenericCrafter);

//defense
log("13");
newBlock("copper-wall-huge",Wall);
newBlock("titanium-wall-huge",Wall);
newBlock("thorium-wall-huge",Wall);
newBlock("defensive-wall",Wall);
newBlock("defensive-wall-large",Wall);
newBlock("defensive-wall-huge",Wall);
newBlock("effective-wall",Wall);
newBlock("effective-wall-large",Wall);
newBlock("two-billion-wall",Wall);

log("14");
newBlock("aluminium-wall",Wall);
newBlock("aluminium-wall-large",Wall);
newBlock("aluminium-wall-huge",Wall);
newBlock("aluminium-lead-wall",Wall);
newBlock("aluminium-lead-wall-large",Wall);
newBlock("aluminium-lead-wall-huge",Wall);
newBlock("silicide-aluminium-wall",Wall);
newBlock("silicide-aluminium-wall-large",Wall);
newBlock("silicide-aluminium-wall-huge",Wall);
newBlock("silicide-wall",Wall);
newBlock("silicide-wall-large",Wall);
newBlock("chromium-wall",Wall);
newBlock("chromium-wall-large",Wall);
newBlock("chromium-wall-huge",Wall);
newBlock("silicide-chromium-wall",Wall);
newBlock("silicide-chromium-wall-large",Wall);
newBlock("silicide-chromium-wall-huge",Wall);
newBlock("mechanical-gate-small",Door);
newBlock("mechanical-gate",Door);
newBlock("mechanical-gate-silicide",Door);
newBlock("automatic-gate",AutoDoor);
newBlock("automatic-gate-silicide",AutoDoor);
newBlock("advanced-plastanium-wall",PowerNode);
newBlock("advanced-plastanium-wall-large",PowerNode);
newBlock("fibralt-wall",RegenProjector);
newBlock("fibralt-wall-large",RegenProjector);
newBlock("blocking-wall",BaseShield);
newBlock("blocking-wall-silicide",BaseShield);
newBlock("surge-shield-wall",ShieldWall);

log("15");
newBlock("ferrum-wall",Wall);
newBlock("ferrum-wall-large",Wall);
newBlock("ferrum-wall-huge",Wall);
newBlock("silicide-ferrum-wall",Wall);
newBlock("silicide-ferrum-wall-large",Wall);
newBlock("silicide-ferrum-wall-huge",Wall);
newBlock("crystallon-wall",PowerTurret);
newBlock("crystallon-wall-large",PowerTurret);

//effect
log("16");
newBlock("sweeper",ConsumeGenerator);
newBlock("overdriver",OverdriveProjector);
newBlock("mend-dome",MendProjector);
newBlock("team-projector-sharded",GenericCrafter);
newBlock("team-projector-crux",GenericCrafter);
newBlock("team-projector-omega",GenericCrafter);
newBlock("team-projector-zenith",GenericCrafter);
newBlock("team-projector-zenith-flipped",GenericCrafter);
newBlock("team-projector-erekir-sharded",GenericCrafter);
newBlock("team-projector-erekir-malis",GenericCrafter);
newBlock("pog-mender",MendProjector);
newBlock("pog-overdriver",OverdriveProjector);
newBlock("sandbox-blast",ConsumeGenerator);
newBlock("force-source",BaseShield);

log("17");
newBlock("mend-point",MendProjector);
newBlock("menderator",MendProjector);
newBlock("mend-globe",MendProjector);
newBlock("overdrive-point",OverdriveProjector);
newBlock("overdrivator",OverdriveProjector);
newBlock("overdrive-globe",OverdriveProjector);
newBlock("forcerator",ForceProjector);
newBlock("plastanium-stool",Router);
newBlock("trap-magnetic",PowerTurret);
newBlock("trap-flame",PowerTurret);
newBlock("trap-blast",PowerTurret);
newBlock("trap-electric",PowerTurret);
newBlock("warp-defender",PointDefenseTurret);
newBlock("spore-bomb",PowerTurret);
newBlock("nuke",PowerTurret);

log("18");
newBlock("core-nucleus-root",CoreBlock);
newBlock("core-singularity-root",CoreBlock);
newBlock("core-nucleus-root-sitrullus",CoreBlock);
newBlock("isomorphic-core-shard",CoreBlock);
newBlock("isomorphic-core-foundation",CoreBlock);
newBlock("isomorphic-core-nucleus",CoreBlock);
newBlock("core-quark",CoreBlock);
newBlock("core-singularity",CoreBlock);
newBlock("core-general",CoreBlock);

log("19");
newBlock("shelf",StorageBlock);
newBlock("bank",StorageBlock);
newBlock("shelf-silicide",StorageBlock);
newBlock("container-silicide",StorageBlock);
newBlock("bank-silicide",StorageBlock);
newBlock("warp-disc",StorageBlock);
newBlock("warp-base",StorageBlock);
newBlock("storage-extender",StorageBlock);

log("20");
newBlock("lamp",GenericCrafter);
newBlock("lamp-alarm",GenericCrafter);
//newBlock("advanced-launch-pad",LaunchPad);
newBlock("advanced-landing-pad",LandingPad);
newBlock("isomorphic-accelerator-small",Accelerator);
newBlock("isomorphic-accelerator",Accelerator);

//fluid
log("21");
newBlock("isomorphic-pump",Pump);
newBlock("pressure-pump",Pump);
newBlock("platform-pump",Pump);
newBlock("chained-pump",Pump);
newBlock("isomorphic-conduit",Conduit);
newBlock("fluid-router",LiquidRouter);
newBlock("fluid-junction",LiquidJunction);
newBlock("isomorphic-bridge-conduit",LiquidBridge);
newBlock("pressure-conduit",ArmoredConduit);
newBlock("platform-bridge-conduit",LiquidBridge);
newBlock("can",LiquidRouter);
newBlock("tank",LiquidRouter);
newBlock("can-silicide",LiquidRouter);
newBlock("tank-silicide",LiquidRouter);
newBlock("silicide-conduit",Conduit);
newBlock("silicide-plated-conduit",ArmoredConduit);
newBlock("silicide-fluid-router",LiquidRouter);
newBlock("silicide-fluid-junction",LiquidJunction);
newBlock("silicide-bridge-conduit",LiquidBridge);
newBlock("silicide-fluid-source",LiquidSource);
newBlock("silicide-fluid-void",LiquidVoid);
//newBlock("fluid-sorter",MultiCrafter);
newBlock("silver-conduit",Conduit);
newBlock("silver-conduit-armored",ArmoredConduit);
newBlock("valve-fluid-distribute",LiquidRouter);
newBlock("valve-fluid-cross",LiquidJunction);
newBlock("silver-bridge",LiquidBridge);

//power
log("22");
newBlock("isomorphic-node",PowerNode);
newBlock("advanced-node",BeamNode);
newBlock("node-blocker",Wall);
newBlock("insulated-node",PowerNode);
newBlock("isomorphic-node-large",PowerNode);
newBlock("advanced-node-large",BeamNode);
newBlock("sector-power-tower",LongPowerNode);
newBlock("power-battery",Battery);
newBlock("silicide-battery",Battery);
newBlock("sodium-sulphur-battery",Battery);
newBlock("charger",GenericCrafter);
newBlock("discharger",ConsumeGenerator);
newBlock("large-combustion-generator",ConsumeGenerator);
newBlock("large-turbine-generator",ConsumeGenerator);
newBlock("internal-combustion-generator",ConsumeGenerator);
newBlock("sodium-reactor",ConsumeGenerator);
newBlock("solar-pad",SolarGenerator);
newBlock("geothermal-generator",ThermalGenerator);
newBlock("lava-thermal-generator",ConsumeGenerator);
newBlock("solid-fuel-cell",ConsumeGenerator);
newBlock("fluid-fuel-cell",ConsumeGenerator);
newBlock("radioactive-thermal-generator",ConsumeGenerator);
newBlock("micro-reactor",NuclearReactor);
newBlock("isomorphic-reactor",NuclearReactor);
newBlock("fusion-reactor",ImpactReactor);

log("23");
newBlock("spot-solar-pad",SolarGenerator);
newBlock("blast-engine",ConsumeGenerator);

log("24");
newBlock("cable",TileableLogicDisplay);
newBlock("battery-node",PowerNode);
newBlock("battery-tower",PowerNode);
newBlock("melon-cell",NuclearReactor);
newBlock("cycle-turbine-generator",ConsumeGenerator);
newBlock("fermentor",ConsumeGenerator);
newBlock("activator-generator",ConsumeGenerator);
newBlock("mect-reactor",ConsumeGenerator);

//production
log("25");
newBlock("mechanical-drill-micro",Drill);
newBlock("mechanical-drill-huge",Drill);
newBlock("isomorphic-drill",Drill);
newBlock("isomorphic-drill-huge",Drill);
newBlock("power-drill",Drill);
newBlock("laser-bore",BeamDrill);
newBlock("beam-drill",Drill);
newBlock("silicide-drill",Drill);
newBlock("hydraulic-drill",Drill);
newBlock("powder-digger",Drill);
newBlock("floor-crusher",BurstDrill);
newBlock("space-digger",Drill);
newBlock("power-well",SolidPump);
newBlock("lava-well",SolidPump);
newBlock("pressure-well",SolidPump);
newBlock("extraction-platform",SolidPump);
newBlock("tissue-cultivator",AttributeCrafter);
newBlock("cultivate-tank",AttributeCrafter);
newBlock("nitroalkoss-cultivator",GenericCrafter);
newBlock("nitroalkoss-cultivator-silicide",GenericCrafter);

log("26");
newBlock("reflector-cultivator",GenericCrafter);

log("27");
newBlock("collector",Drill);
newBlock("magnetic-digger",Drill);
newBlock("mechanical-well",SolidPump);
newBlock("rot-chamber",AttributeCrafter);

//turrets
log("28");
newBlock("click",ItemTurret);
newBlock("frag",ItemTurret);
newBlock("rise",ItemTurret);
newBlock("bake",ItemTurret);
newBlock("pulse",PowerTurret);
newBlock("waterer",LiquidTurret);
newBlock("beat",ItemTurret);
newBlock("crack",ItemTurret);
newBlock("shock",PowerTurret);

log("29");
newBlock("buffet",ItemTurret);
newBlock("burn",ContinuousLiquidTurret);
newBlock("dot",ItemTurret);
newBlock("spurt",LiquidTurret);
newBlock("snipe",ItemTurret);
newBlock("shell",ItemTurret);
newBlock("halberd",PowerTurret);

log("30");
newBlock("buster",ItemTurret);
newBlock("parasite",ItemTurret);
newBlock("chain",PowerTurret);
newBlock("sweep",PowerTurret);
newBlock("stab",ItemTurret);
newBlock("sans",LiquidTurret);

log("31");
newBlock("double",ItemTurret);
newBlock("burst",ItemTurret);
newBlock("ash",ItemTurret);
newBlock("pantype",ItemTurret);
newBlock("meteor",ItemTurret);
newBlock("vector",PowerTurret);
newBlock("guarden",PowerTurret);
newBlock("incandescence",PowerTurret);
newBlock("melonic-array-pillar",PowerTurret);

//units
log("32");
newBlock("gigantic-payload-conveyor",PayloadConveyor);
newBlock("world-payload-conveyor",PayloadConveyor);

log("33");
newBlock("ground-fabricator",UnitFactory);
newBlock("air-fabricator",UnitFactory);
newBlock("naval-fabricator",UnitFactory);
newBlock("special-fabricator",UnitFactory);
newBlock("integrated-constructor",UnitFactory);
newBlock("platform-theta",UnitCargoLoader);
newBlock("platform-lambda",UnitCargoLoader);
newBlock("platform-sigma",UnitCargoLoader);
newBlock("isomorphic-additive-reconstructor",Reconstructor);
newBlock("isomorphic-multiplicative-reconstructor",Reconstructor);
newBlock("junior-armorcar-reconstructor",Reconstructor);
newBlock("junior-hovership-reconstructor",Reconstructor);
newBlock("junior-crabbot-reconstructor",Reconstructor);
newBlock("senior-armorcar-reconstructor",Reconstructor);
newBlock("senior-hovership-reconstructor",Reconstructor);
newBlock("senior-crabbot-reconstructor",Reconstructor);
newBlock("super-reconstructor",Reconstructor);
newBlock("ultra-reconstructor",Reconstructor);
newBlock("junior-refabricator",Reconstructor);
newBlock("senior-refabricator",Reconstructor);
newBlock("isomorphic-repair-point",RepairTurret);

log("34");
newBlock("payload-rail-small",PayloadConveyor);
newBlock("payload-rail",PayloadConveyor);
newBlock("payload-rail-router",PayloadRouter);
newBlock("payload-rail-large",PayloadConveyor);
newBlock("payload-rail-router-large",PayloadRouter);
newBlock("cobalt-payload-rail",PayloadConveyor);
newBlock("cobalt-payload-rail-router",PayloadRouter);
newBlock("cobalt-payload-rail-large",PayloadConveyor);
newBlock("cobalt-payload-rail-router-large",PayloadRouter);
newBlock("warp-teleporter",PayloadAmmoTurret);
newBlock("assemble-packer",Constructor);
newBlock("assemble-selector1",UnitAssemblerModule);
newBlock("assemble-selector2",UnitAssemblerModule);
newBlock("assemble-selector3",UnitAssemblerModule);
newBlock("super-assemble-pack",Wall);
newBlock("ultra-assemble-pack",Wall);
newBlock("hyper-assemble-pack",Wall);
newBlock("special-assembler",UnitAssembler);
newBlock("super-assembler",UnitAssembler);
newBlock("ultra-assembler",UnitAssembler);
newBlock("boss-assembler",UnitAssembler);

log("35");
newBlock("general-payload-conveyor",PayloadConveyor);
newBlock("small-unit-constructor",UnitFactory);
newBlock("small-unit-constructor-sharded",UnitFactory);
newBlock("standard-constructor",UnitFactory);
newBlock("standard-constructor-sharded",UnitFactory);
newBlock("elite-upgrader",Reconstructor);
newBlock("elite-upgrader-sharded",Reconstructor);
newBlock("melon-repair-bay",RepairTower);
newBlock("watermelon-printer",Constructor);
newBlock("element-printer",Constructor);
newBlock("element-ferric",GenericCrafter);
newBlock("element-silver",GenericCrafter);
newBlock("element-melonic",GenericCrafter);
newBlock("element-effective",GenericCrafter);

//logic
log("36");
newBlock("isomorphic-message",MessageBlock);
newBlock("isomorphic-switch",SwitchBlock);
newBlock("isomorphic-processor",LogicBlock);
newBlock("isomorphic-memory",MemoryBlock);
newBlock("quantum-processor",LogicBlock);
newBlock("quantum-memory-cell",MemoryBlock);

//end
log("complete");